import { expect, test } from "@playwright/test";
import { confirmVehicle, lockSteeringIfPrompted, presentUntilVisible } from "./start-helpers";
import { WEBGPU_TEST_OPTIONS } from "./browser-options";

test.use(WEBGPU_TEST_OPTIONS);
for (const renderer of ["WebGPU", "Canvas"] as const) test(`${renderer}: desktop Options hub, door action and archive layout`, async ({ page }, info) => {
  test.setTimeout(90_000);
  await page.setViewportSize({ width: 1440, height: 960 });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  if (renderer === "Canvas") await page.addInitScript(() => Object.defineProperty(navigator, "gpu", { value: undefined }));
  await page.clock.install();
  await page.goto("/");
  await expect(page.locator(".menu-screen .control-strip, .menu-options-bar")).toHaveCount(0);
  await page.getByRole("button", { name: "OPTIONS", exact: true }).click();
  await expect(page.getByRole("button", { name: "BACK TO MENU", exact: true })).toBeFocused();
  await expect(page.getByRole("button", { name: /RESUME|END FREE RUN/ })).toHaveCount(0);
  await page.keyboard.press("Escape");
  await expect(page.locator(".arcade-shell")).toHaveClass(/mode-menu/);
  await page.getByRole("button", { name: /Start Free Run with arcade/ }).click();
  await confirmVehicle(page);
  await page.getByRole("button", { name: /Choose STREET ACE/ }).click();
  await lockSteeringIfPrompted(page);
  await page.clock.fastForward(3600);
  await expect(page.locator(".arcade-shell.mode-playing")).toBeVisible();
  await page.clock.runFor(100);
  await expect(page.locator(".pause-button")).toHaveCount(0);
  const score = (await page.locator(".score-card").boundingBox())!;
  const multi = (await page.locator(".combo-sticker").boundingBox())!;
  expect(multi.y).toBeGreaterThan(score.y + score.height);
  expect(Math.abs(multi.x + multi.width - score.x - score.width)).toBeLessThan(12);
  const positions: number[] = [];
  for (const camera of ["HIGH", "LOW", "CAB", "FIXED"]) {
    await page.keyboard.press("Escape");
    await expect(page.getByRole("button", { name: "RESUME FREE RUN", exact: true })).toBeFocused();
    await page.getByRole("group", { name: "Camera view", exact: true }).getByRole("button", { name: camera, exact: true }).click();
    await page.getByRole("button", { name: "RESUME FREE RUN", exact: true }).click();
    await page.clock.runFor(700);
    const exit = page.locator(".interaction-prompt.is-taxi-exit");
    await expect(exit).toBeInViewport({ ratio: 1 });
    await exit.click({ trial: true });
    positions.push(Math.round((await exit.boundingBox())!.y));
  }
  expect(new Set(positions).size).toBeGreaterThan(2);
  await page.getByRole("button", { name: "Pause game", exact: true }).click();
  await expect(page.getByRole("tab", { name: "DRIVE & OPTIONS" })).toHaveAttribute("aria-selected", "true");
  await page.screenshot({ path: info.outputPath("desktop-pause.png") });
  await page.setViewportSize({ width: 1024, height: 720 });
  await expect(page.getByRole("button", { name: "RESUME FREE RUN", exact: true })).toBeInViewport({ ratio: 1 });
  await expect(page.getByRole("button", { name: "END FREE RUN · BANK FARE", exact: true })).toBeInViewport({ ratio: 1 });
  await page.screenshot({ path: info.outputPath("compact-pause.png") });
  await page.getByRole("button", { name: "OPTIONS · DEV MODE", exact: true }).click();
  await page.getByRole("checkbox", { name: /DEV MODE/ }).check();
  await page.getByRole("button", { name: "JUMP TO PICKUP", exact: true }).click();
  await page.getByRole("button", { name: "CLOSE OPTIONS", exact: true }).click();
  await page.getByRole("button", { name: "RESUME FREE RUN", exact: true }).click();
  await presentUntilVisible(page, page.locator(".fare-impact--pickup"));
  await page.clock.fastForward(4000);
  await page.clock.runFor(100);
  const stack = page.locator(".fare-card-stack");
  await expect(stack).toBeVisible();
  const mapBox = (await page.locator(".gps-panel").boundingBox())!;
  const stackBox = (await stack.boundingBox())!;
  expect(stackBox.y).toBeGreaterThan(mapBox.y + mapBox.height);
  expect(stackBox.y - mapBox.y - mapBox.height).toBeLessThan(40);
  expect(Math.abs(stackBox.x - mapBox.x)).toBeLessThan(8);
  await page.screenshot({ path: info.outputPath("desktop-hud.png") });
  await stack.click();
  await expect(page.getByRole("tab", { name: /FARE DECK/ })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("region", { name: "Run fare card deck", exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath("fare-archive.png") });
  await page.keyboard.press("Escape");
  await expect(page.locator(".arcade-shell.mode-playing")).toBeVisible();
  expect(errors).toEqual([]);
});
