/** Original lesson copy; scientific references and topic map: docs/accord-events.md. */
export const QUANTUM_FACTS = [
  { title: "A LITTLE SUPERPOSITION", level: "FIRST PRINCIPLES", symbol: "ψ", text: "A quantum state can combine several possible measurement outcomes. Their amplitudes can interfere, reinforcing or cancelling one another. Measuring gives one outcome, with probabilities set by the state.", aside: "The Accord, sadly, must still pick one lane." },
  { title: "SPOOKY. STILL NO SHORTCUT.", level: "ENTANGLEMENT", symbol: "↔", text: "Entangled particles share a joint quantum state. Their measurement results can be correlated in ways classical local models cannot explain. Those correlations cannot send a message faster than light.", aside: "Even quantum physics cannot text your destination ahead of you." },
  { title: "THROUGH THE IMPOSSIBLE", level: "QUANTUM TUNNELING", symbol: "≈", text: "A quantum particle can have a nonzero chance of crossing an energy barrier that would stop a classical particle with the same energy. Its wavefunction extends into and sometimes beyond the barrier.", aside: "Please do not try this with the Accord and a brick wall." },
  { title: "LIGHT COMES IN PACKETS", level: "PHOTONS", symbol: "hν", text: "Light exchanges energy in discrete packets called photons. A photon’s energy is its frequency multiplied by Planck’s constant: E = hν. Higher-frequency blue light has more energy per photon than red light.", aside: "The neon outside is doing physics all night." },
  { title: "PRECISION HAS A LIMIT", level: "UNCERTAINTY", symbol: "ℏ", text: "Position and momentum cannot both have arbitrarily small spreads in the same quantum state. Their standard deviations obey Δx Δp ≥ ℏ/2. This is a property of quantum states, even with ideal instruments.", aside: "That is not an excuse for missing the next turn." },
  { title: "NO QUANTUM PHOTOCOPIER", level: "NO-CLONING", symbol: "≠", text: "No physical operation can perfectly copy every arbitrary unknown quantum state. Copying ordinary digital data is fine; a universal copier for unknown quantum states is ruled out by quantum mechanics.", aside: "One Accord with this much personality is probably enough." },
  { title: "AN ATOM’S OWN COLORS", level: "ENERGY LEVELS", symbol: "ΔE", text: "Bound electrons in atoms occupy allowed energy levels. When an atom changes between levels, it can absorb or emit a photon whose energy matches the difference. Those transitions give elements distinctive spectral lines.", aside: "Think of it as an atomic signature in light." },
  { title: "A QUBIT IS NOT A CHEAT CODE", level: "QUANTUM COMPUTING", symbol: "|ψ⟩", text: "A qubit can be in a superposition of 0 and 1, but a measurement returns just one result. Quantum algorithms use interference and sometimes entanglement to make useful answers more likely. They do not simply reveal every possible answer at once.", aside: "We still have to do this fare one destination at a time." },
  { title: "ONE AT A TIME. STILL STRIPES.", level: "DOUBLE-SLIT EXPERIMENT", symbol: "Ⅱ",
    text: "Send electrons through a suitable double-slit apparatus one at a time. Each detection makes one spot, but many spots build an interference pattern when the paths remain coherent and indistinguishable. The pattern is not caused by electrons bumping into one another.",
    aside: "One passenger at a time can also build a surprisingly large queue." },
  { title: "THE PATH LEAVES A CLUE", level: "WHICH-PATH INFORMATION", symbol: "?",
    text: "In a two-path experiment, a detector that leaves distinguishable records of the paths removes their interference when those records are ignored. A person does not have to read the detector. The physical interaction and the information it leaves behind are what matter.",
    aside: "The universe does not need someone watching the dashcam." },
  { title: "SQUARE BEFORE YOU GUESS", level: "THE BORN RULE", symbol: "|α|²",
    text: "Quantum theory assigns a probability amplitude to an outcome. The probability is the squared magnitude of that amplitude: P = |α|². For indistinguishable alternatives, add their amplitudes first, then square. Adding probabilities instead would miss interference.",
    aside: "A rare situation where the order of the paperwork changes reality's prediction." },
  { title: "IT IS A PHASE. A USEFUL ONE.", level: "RELATIVE PHASE", symbol: "φ",
    text: "Two superpositions can give the same probabilities in one measurement yet behave differently in another because their relative phases differ. Relative phase controls interference. Multiplying an entire state by one common phase, called a global phase, changes no measurement probabilities.",
    aside: "Your driver's current phase is explaining phases." },
  { title: "MATTER HAS A WAVELENGTH", level: "DE BROGLIE WAVES", symbol: "λ",
    text: "A particle with a definite momentum p has a de Broglie wavelength λ = h/p. Electrons can therefore diffract, producing patterns when scattered by a crystal. For an ordinary moving car, the associated wavelength is far too tiny to give visible wave effects in traffic.",
    aside: "The Accord remains subject to the full width of that parking space." },
  { title: "STATIONARY IS A TECHNICAL TERM", level: "ENERGY EIGENSTATES", symbol: "E",
    text: "For a system whose Hamiltonian does not change with time, a state of definite energy gains only a global phase as time passes. Its position probabilities stay unchanged. Calling this a stationary state does not mean a particle is a tiny object frozen at one particular place.",
    aside: "A stationary taxi has a much simpler explanation: you parked it." },
  { title: "A VERY STRICT LITTLE BOX", level: "PARTICLE IN A BOX", symbol: "n²",
    text: "In the ideal model of a particle trapped between infinitely high walls, the wavefunction must vanish at both walls. Only certain standing waves fit. Their energies are discrete and grow as n², where n starts at 1. Narrowing the box raises all these energy levels.",
    aside: "This is not a scientific endorsement of smaller apartments." },
  { title: "EVEN THE GROUND FLOOR HAS ENERGY", level: "ZERO-POINT ENERGY", symbol: "½ℏω",
    text: "A quantum harmonic oscillator has energy levels E = (n + 1/2)ℏω. Its lowest state sits above the minimum of the classical potential energy. This zero-point energy is not a fuel tank you can drain: the ground state is already the lowest available state of that oscillator.",
    aside: "We will still be stopping for petrol." },
  { title: "SPIN WITHOUT A TINY AXLE", level: "INTRINSIC ANGULAR MOMENTUM", symbol: "½",
    text: "An electron has intrinsic angular momentum called spin. It is not a miniature solid ball rotating around an axle. Measuring its spin component along a chosen axis gives one of two values, +ℏ/2 or −ℏ/2. The chosen direction determines which measurement you perform.",
    aside: "Tiny tyres would have made this considerably easier to explain." },
  { title: "ASK A DIFFERENT QUESTION", level: "INCOMPATIBLE MEASUREMENTS", symbol: "x / z",
    text: "Prepare an electron with spin up along z. An ideal measurement along x gives either result with equal probability. After that x measurement, measuring z again can give up or down. Measurements along different axes are not simply reading a list of answers already stored inside.",
    aside: "Your passenger is considering asking a different driver." },
  { title: "THIS STATE IS OCCUPIED", level: "PAULI EXCLUSION", symbol: "×2",
    text: "Two identical fermions, such as electrons, cannot occupy the same one-particle quantum state. Spin is part of that state: two electrons can share a spatial orbital if their spin states differ. This exclusion rule helps determine atomic shell structure and the patterns of chemistry.",
    aside: "An impressively fundamental reason to respect assigned seating." },
  { title: "BOSONS CAN SHARE", level: "PARTICLE STATISTICS", symbol: "+",
    text: "Bosons have integer spin; fermions have half-integer spin. Identical bosons can occupy the same quantum state, while identical fermions obey the exclusion principle. This difference in their quantum statistics helps explain why collections of photons and collections of electrons behave differently.",
    aside: "Neither category gives this taxi an extra passenger seat." },
  { title: "A CROWD IN ONE STATE", level: "BOSE–EINSTEIN CONDENSATES", symbol: "Ψ",
    text: "Cool a suitable dilute gas of bosonic atoms far enough and a large fraction can occupy the same lowest-energy state. That is a Bose–Einstein condensate. The atoms have not fused into one giant atom; their shared quantum state produces collective behaviour over the cloud.",
    aside: "Group travel has become unexpectedly technical." },
  { title: "A FLUID WITH OTHER IDEAS", level: "SUPERFLUIDITY", symbol: "He",
    text: "Below its transition temperature, liquid helium-4 develops a superfluid component that can flow without ordinary viscous resistance. Its behaviour is described by a collective quantum state. Rotation can form vortices whose circulation comes in discrete units rather than arbitrary amounts.",
    aside: "Still a terrible substitute for the fluid recommended in the owner's manual." },
  { title: "ELECTRONS TEAM UP", level: "SUPERCONDUCTIVITY", symbol: "2e",
    text: "In conventional superconductors, electrons form correlated Cooper pairs and a collective quantum state. Below the relevant temperature, current and magnetic-field limits, the material can carry direct current without electrical resistance. That does not remove the energy cost of running an attached device.",
    aside: "The heated seats have not discovered free electricity." },
  { title: "A CURRENT ACROSS A GAP", level: "THE JOSEPHSON EFFECT", symbol: "δ",
    text: "Two superconductors separated by a thin insulating barrier can carry a supercurrent through quantum tunnelling. The current depends on the relative phase of their superconducting states. A steady voltage across the junction makes that phase change, producing an oscillating supercurrent.",
    aside: "Your driver has somehow made a gap sound busy." },
  { title: "THE SQUID HAS NO TENTACLES", level: "QUANTUM MAGNETOMETRY", symbol: "Φ",
    text: "A SQUID is a superconducting quantum interference device. In a common design, a superconducting loop contains two Josephson junctions. Magnetic flux through the loop changes their interference and the device's electrical response, letting it detect extremely small changes in magnetic field.",
    aside: "Please stop looking in the boot for a marine animal." },
  { title: "A MAP MADE BY TUNNELLING", level: "SCANNING TUNNELLING MICROSCOPY", symbol: "↕",
    text: "Bring a sharp conducting tip very close to a conducting surface and apply a voltage. Electrons can tunnel across the tiny gap. Because the current depends strongly on the separation and electronic states, scanning the tip can reveal features on the scale of individual atoms.",
    aside: "Finally, a map with more detail than the driver actually needs." },
  { title: "LIGHT ENCOURAGES MORE LIGHT", level: "STIMULATED EMISSION", symbol: "ν",
    text: "An excited atom can be stimulated by light to emit into the same optical mode, adding light with matching frequency and phase. A laser combines amplification with a way to select modes, often an optical cavity. Energy supplied by a pump keeps the amplification going.",
    aside: "The headlights are not receiving this upgrade." },
  { title: "BRIGHTER IS NOT ALWAYS ENOUGH", level: "THE PHOTOELECTRIC EFFECT", symbol: "hν",
    text: "In ordinary single-photon photoemission, a photon must supply enough energy to free an electron from a material. The threshold depends on photon frequency and the material's work function. Increasing brightness adds photons; it does not increase the energy carried by each one.",
    aside: "An argument for substance over enthusiasm, delivered very enthusiastically." },
  { title: "ATOMS KEEP THE BEAT", level: "ATOMIC CLOCKS", symbol: "Cs",
    text: "An atomic clock compares an oscillator with a particular transition between atomic energy levels. Feedback keeps the oscillator tuned to that reference, and counting its cycles measures time. The atoms provide a reproducible frequency, rather than tiny mechanical hands moving around a dial.",
    aside: "A beautifully precise way to establish that your passenger is late." },
  { title: "SQUEEZE THE NOISE", level: "QUANTUM OPTICS", symbol: "Δ",
    text: "Squeezed light reduces quantum uncertainty in one field quadrature at the expense of greater uncertainty in its conjugate quadrature. The uncertainty principle still holds. With the right choice of squeezing, an instrument can reduce noise in the quantity it needs to measure, as in gravitational-wave detectors.",
    aside: "Squeezing the steering wheel does not provide the same benefit." },
  { title: "BELL PUT A LIMIT ON THE GUESS", level: "BELL INEQUALITIES", symbol: "≤",
    text: "Bell inequalities bound correlations for models with local, pre-existing answers and independently chosen measurement settings. Experiments violate these bounds, as quantum mechanics predicts. This rules out that combination of assumptions; it does not enable faster-than-light messages.",
    aside: "Your driver's guess about the traffic has undergone considerably less testing." },
  { title: "TELEPORT THE STATE, NOT THE TAXI", level: "QUANTUM TELEPORTATION", symbol: "→ψ",
    text: "Quantum teleportation transfers an unknown quantum state using shared entanglement, a joint measurement and a classical message. The receiver uses the message to recover the state. The original state is not kept as a spare, and the required classical communication prevents faster-than-light delivery.",
    aside: "You, your luggage, and this Accord are completing the trip conventionally." },
  { title: "THE ENVIRONMENT JOINS IN", level: "DECOHERENCE", symbol: "ψ",
    text: "When a quantum system becomes entangled with its surroundings, interference between its alternatives can become inaccessible in measurements of the system alone. This is decoherence. It helps explain why delicate quantum interference is hard to maintain in warm, noisy, everyday surroundings.",
    aside: "A polite scientific description of the inside of this taxi." },
  { title: "A COIN FLIP IS NOT A QUBIT", level: "MIXTURES AND SUPERPOSITIONS", symbol: "ρ",
    text: "An equal mixture of 0 and 1 and a coherent equal superposition both give fifty-fifty results when measured in the 0/1 basis. But another measurement can distinguish their statistics. A superposition retains a relative phase that an ordinary random mixture of those two states lacks.",
    aside: "The loose change in the cup holder remains ordinary loose change." },
  { title: "THE AVERAGE MAY NEVER HAPPEN", level: "EXPECTATION VALUES", symbol: "⟨E⟩",
    text: "An expectation value is the probability-weighted average of possible measurement outcomes across many identically prepared systems. It need not be one of the individual outcomes. A system with only two possible measured energies can have an average energy halfway between them.",
    aside: "The average passenger may enjoy this. We are still collecting data." },
  { title: "A QUANTUM COLOUR PALETTE", level: "LIGHT-EMITTING DIODES", symbol: "LED",
    text: "In an LED, electrons and holes recombine in a semiconductor and can release energy as photons. The material's allowed energy bands and band gap help set the light's colour. Changing semiconductor composition lets engineers design emitters for different parts of the spectrum.",
    aside: "Even the dashboard has quietly been taking this class." },
  { title: "GATES THAT CAN GO BACKWARDS", level: "UNITARY OPERATIONS", symbol: "U†U",
    text: "An ideal quantum gate acts by a unitary transformation: it preserves total probability and has an inverse. This makes the gate reversible in principle. Measurement and uncontrolled noise are different processes; you cannot simply undo an arbitrary measurement by applying a gate to the measured system.",
    aside: "Reverse gear is considerably less mathematically demanding." },
  { title: "TWO HADAMARDS MAKE A RETURN TRIP", level: "HADAMARD INTERFERENCE", symbol: "H²",
    text: "Apply a Hadamard gate to a qubit in state 0 and it becomes an equal superposition of 0 and 1. Apply the same gate again, without an intervening measurement or noise, and it returns to 0. Interference makes this unlike flipping an ordinary coin twice.",
    aside: "A return journey with unusually good cancellation policies." },
  { title: "A CONTROL WITH QUANTUM CONSEQUENCES", level: "THE CNOT GATE", symbol: "⊕",
    text: "A controlled-NOT flips a target qubit when its control is 1 and leaves it alone when the control is 0. If the control starts in an equal superposition and the target in 0, the result is entanglement. It does not create two independent copies of the control's unknown state.",
    aside: "The passenger has asked whether the radio has a simpler control." },
  { title: "A SPHERE FULL OF STATES", level: "THE BLOCH SPHERE", symbol: "○",
    text: "Every pure state of one qubit can be represented by a point on the surface of the Bloch sphere. Its coordinates describe a quantum state, not a particle's location in ordinary space. Mixed states lie inside the sphere; the centre represents a completely mixed qubit.",
    aside: "It is a useful map. It still will not get us to the airport." },
  { title: "FIX THE ERROR, KEEP THE SECRET", level: "QUANTUM ERROR CORRECTION", symbol: "✓",
    text: "Quantum error correction encodes information across several physical qubits. Carefully chosen measurements reveal an error syndrome without revealing the encoded logical state. A correction can then repair certain errors. The scheme spreads information through correlations rather than making forbidden copies of an unknown qubit.",
    aside: "Your driver would also like corrections without a detailed account of every mistake." },
  { title: "ONE QUBIT, MANY SUPPORTING ACTORS", level: "LOGICAL AND PHYSICAL QUBITS", symbol: "L/P",
    text: "A physical qubit is an actual controllable quantum system. A logical qubit is encoded across physical qubits using an error-correcting code. Extra qubits and repeated checks can protect the information, but only when noise and operations meet the requirements of the scheme. More qubits alone are not a guarantee.",
    aside: "A surprisingly large team is helping one bit get through its day." },
  { title: "A SEARCH WITH A SQUARE-ROOT ADVANTAGE", level: "GROVER'S ALGORITHM", symbol: "√N",
    text: "For an unstructured search with one marked solution among N candidates, Grover's algorithm needs on the order of √N oracle queries rather than order N classical queries. This is a quadratic advantage in the query model. Building the oracle and running the hardware still have costs.",
    aside: "It will not instantly find the keys underneath the driver's seat." },
  { title: "FACTORING TAKES A DIFFERENT ROUTE", level: "SHOR'S ALGORITHM", symbol: "aˣ",
    text: "Shor's factoring algorithm turns part of the problem into finding the period of a modular arithmetic function. A quantum computer can solve that part efficiently, followed by classical calculations to obtain factors. Useful large-scale runs require sufficiently reliable hardware; the algorithm is not a shortcut every small device can already deliver.",
    aside: "The Accord is still using its calculator for splitting the lunch bill." },
  { title: "LET QUANTUM STUDY QUANTUM", level: "QUANTUM SIMULATION", symbol: "Ĥ",
    text: "A quantum simulator uses a controllable quantum system to investigate another one, such as electrons in a material. It can encode a model in gates or engineer an analogous physical system. The goal is to learn useful properties, not to print every amplitude of an enormous quantum state.",
    aside: "Simulating a taxi driver who stops talking is a separate research programme." },
  { title: "CHECK WHO MIGHT BE LISTENING", level: "QUANTUM KEY DISTRIBUTION", symbol: "κ",
    text: "In BB84, people encode and measure quantum states using different bases, then compare selected information over an authenticated classical channel. Eavesdropping can introduce detectable errors. They estimate errors and process or discard the data; secure keys depend on the protocol's assumptions and the actual devices.",
    aside: "The passenger would prefer a channel that occasionally stops transmitting." },
  { title: "COOLING WITH LIGHT", level: "LASER COOLING", symbol: "p",
    text: "Photons carry momentum. With suitably tuned laser beams, an atom moving toward a beam can be more likely to absorb light opposing its motion. Absorption and emission cycles can reduce the atoms' random motion overall, cooling the gas. Shining arbitrary light on something does not automatically cool it.",
    aside: "Please continue using the air-conditioning button." },
  { title: "A USEFUL FLAW IN A DIAMOND", level: "QUANTUM SENSING", symbol: "NV",
    text: "A nitrogen-vacancy centre is a defect in diamond: a nitrogen atom sits beside a missing carbon atom. Its electron spin energy levels respond to magnetic fields. Researchers can control and read those states with microwaves and light, turning an atomic-scale flaw into a sensitive measuring tool.",
    aside: "The scratches on this Accord have yet to develop comparable capabilities." },
] as const;
